In [1]:
!pip install kaggle
#importing kaggle api / library

Collecting kaggle
  Obtaining dependency information for kaggle from https://files.pythonhosted.org/packages/75/f6/cccedb8db42beac1c5d7cfa57d5b800b90ef91118833972af3f7b5e159c8/kaggle-1.7.4.2-py3-none-any.whl.metadata
  Downloading kaggle-1.7.4.2-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: bleach in c:\users\windows\.anaconda\lib\site-packages (from kaggle) (4.1.0)
Requirement already satisfied: certifi>=14.05.14 in c:\users\windows\.anaconda\lib\site-packages (from kaggle) (2023.7.22)
Requirement already satisfied: charset-normalizer in c:\users\windows\.anaconda\lib\site-packages (from kaggle) (2.0.4)
Requirement already satisfied: idna in c:\users\windows\.anaconda\lib\site-packages (from kaggle) (3.4)
Collecting protobuf (from kaggle)
  Obtaining dependency information for protobuf from https://files.pythonhosted.org/packages/97/e9/7b9f1b259d509aef2b833c29a1f3c39185e2bf21c9c1be1cd11c22cb2149/protobuf-6.30.2-cp310-abi3-win_amd64.whl.metadata
  Downloading protobuf-6.30.2-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\windows\.anaconda\lib\site-packages (from kaggle) (2.8.2)
Requirement already satisfied: python-slugify in c:\users\windows\.anaconda\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: requests in c:\users\windows\.anaconda\lib\site-packages (from kaggle) (2.31.0)
Requirement already satisfied: setuptools>=21.0.0 in c:\users\windows\.anaconda\lib\site-packages (from kaggle) (68.0.0)
Requirement already satisfied: six>=1.10 in c:\users\windows\.anaconda\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: text-unidecode in c:\users\windows\.anaconda\lib\site-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in c:\users\windows\.anaconda\lib\site-packages (from kaggle) (4.65.0)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\windows\.anaconda\lib\site-packages (from kaggle) (1.26.16)
Requirement already satisfied: webencodings in c:\users\windows\.anaconda\lib\site-packages (from kaggle) (0.5.1)
Requirement already satisfied: packaging in c:\users\windows\.anaconda\lib\site-packages (from bleach->kaggle) (23.0)
Requirement already satisfied: colorama in c:\users\windows\.anaconda\lib\site-packages (from tqdm->kaggle) (0.4.6)
Downloading kaggle-1.7.4.2-py3-none-any.whl (173 kB)
   ---------------------------------------- 0.0/173.2 kB ? eta -:--:--
   -------------------------- ------------- 112.6/173.2 kB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 173.2/173.2 kB 3.5 MB/s eta 0:00:00
Downloading protobuf-6.30.2-cp310-abi3-win_amd64.whl (431 kB)
   ---------------------------------------- 0.0/431.0 kB ? eta -:--:--
   ------------------ --------------------- 194.6/431.0 kB 4.0 MB/s eta 0:00:01
   -------------------------- ------------- 286.7/431.0 kB 3.0 MB/s eta 0:00:01
   ------------------------------------- -- 399.4/431.0 kB 3.1 MB/s eta 0:00:01
   ---------------------------------------- 431.0/431.0 kB 2.5 MB/s eta 0:00:00
Installing collected packages: protobuf, kaggle
Successfully installed kaggle-1.7.4.2 protobuf-6.30.2

In [5]:
import kaggle
#importing kaggle

In [36]:
#Downloading the kaggle dataset

!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv: Skipping, found more recently modified local copy (use --force to force download)

In [40]:
import zipfile

# Use raw string literal to avoid escape character issues
zip_ref = zipfile.ZipFile(r"C:\Users\Windows\Downloads\orders.csv.zip")
zip_ref.extractall(r"C:\Users\Windows\Downloads")  # Extract the file to the Downloads folder
zip_ref.close()  # Close the zip file

print("File extracted successfully!")

File extracted successfully!

In [47]:
#Reading data and handling null values
import pandas as pd

# Use the correct path to the extracted CSV
df = pd.read_csv(r"C:\Users\Windows\Downloads\orders.csv")

# Preview the data
print(df.head(20))

    Order Id  Order Date       Ship Mode      Segment        Country  \
0          1  2023-03-01    Second Class     Consumer  United States
1          2  2023-08-15    Second Class     Consumer  United States
2          3  2023-01-10    Second Class    Corporate  United States
3          4  2022-06-18  Standard Class     Consumer  United States
4          5  2022-07-13  Standard Class     Consumer  United States
5          6  2022-03-13   Not Available     Consumer  United States
6          7  2022-12-28  Standard Class     Consumer  United States
7          8  2022-01-25  Standard Class     Consumer  United States
8          9  2023-03-23   Not Available     Consumer  United States
9         10  2023-05-16  Standard Class     Consumer  United States
10        11  2023-03-31   Not Available     Consumer  United States
11        12  2023-12-25   Not Available     Consumer  United States
12        13  2022-02-11  Standard Class     Consumer  United States
13        14  2023-07-18  Standard Class     Consumer  United States
14        15  2023-11-09         unknown  Home Office  United States
15        16  2022-06-18  Standard Class  Home Office  United States
16        17  2022-02-04  Standard Class     Consumer  United States
17        18  2023-08-04    Second Class     Consumer  United States
18        19  2022-01-23    Second Class     Consumer  United States
19        20  2022-01-11    Second Class     Consumer  United States

               City           State  Postal Code   Region         Category  \
0         Henderson        Kentucky        42420    South        Furniture
1         Henderson        Kentucky        42420    South        Furniture
2       Los Angeles      California        90036     West  Office Supplies
3   Fort Lauderdale         Florida        33311    South        Furniture
4   Fort Lauderdale         Florida        33311    South  Office Supplies
5       Los Angeles      California        90032     West        Furniture
6       Los Angeles      California        90032     West  Office Supplies
7       Los Angeles      California        90032     West       Technology
8       Los Angeles      California        90032     West  Office Supplies
9       Los Angeles      California        90032     West  Office Supplies
10      Los Angeles      California        90032     West        Furniture
11      Los Angeles      California        90032     West       Technology
12          Concord  North Carolina        28027    South  Office Supplies
13          Seattle      Washington        98103     West  Office Supplies
14       Fort Worth           Texas        76106  Central  Office Supplies
15       Fort Worth           Texas        76106  Central  Office Supplies
16          Madison       Wisconsin        53711  Central  Office Supplies
17      West Jordan            Utah        84084     West  Office Supplies
18    San Francisco      California        94109     West  Office Supplies
19    San Francisco      California        94109     West       Technology

   Sub Category       Product Id  cost price  List Price  Quantity  \
0     Bookcases  FUR-BO-10001798         240         260         2
1        Chairs  FUR-CH-10000454         600         730         3
2        Labels  OFF-LA-10000240          10          10         2
3        Tables  FUR-TA-10000577         780         960         5
4       Storage  OFF-ST-10000760          20          20         2
5   Furnishings  FUR-FU-10001487          50          50         7
6           Art  OFF-AR-10002833          10          10         4
7        Phones  TEC-PH-10002275         860         910         6
8       Binders  OFF-BI-10003910          20          20         3
9    Appliances  OFF-AP-10002892          90         110         5
10       Tables  FUR-TA-10001539        1470        1710         9
11       Phones  TEC-PH-10002033         750         910         4
12        Paper  OFF-PA-10002365          20          20         3
13      Binders  OFF-BI-10003656         360         410         3
14   Appliances  OFF-AP-10002311          60          70         5
15      Binders  OFF-BI-10000756           0           0         3
16      Storage  OFF-ST-10004186         610         670         6
17      Storage  OFF-ST-10000107          60          60         2
18          Art  OFF-AR-10003056          10          10         2
19       Phones  TEC-PH-10001949         170         210         3

    Discount Percent
0                  2
1                  3
2                  5
3                  2
4                  5
5                  3
6                  3
7                  5
8                  2
9                  3
10                 3
11                 3
12                 3
13                 2
14                 5
15                 5
16                 3
17                 4
18                 4
19                 3

In [49]:
#types if ship mode - unique gives the unique values of shipment modes
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', 'Not Available', 'unknown',
       'First Class', nan, 'Same Day'], dtype=object)

In [54]:
#replace these not avaible and unknown values as null /nan

df.replace(['Not Available', 'unknown'], pd.NA, inplace=True)
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [65]:
#renaming the column names
df.columns
#change the column names to one pattern 
#1. use json and create a key value pair to replace each column manually
#2. instead use the python and convert the column names to str obj then to lower case then replace the spaces with underscore to acheive the default way

Index(['order id', 'order date', 'ship mode', 'segment', 'country', 'city',
       'state', 'postal code', 'region', 'category', 'sub category',
       'product id', 'cost price', 'list price', 'quantity',
       'discount percent'],
      dtype='object')

In [62]:
#Changing the names of the columns to lower case
df.columns=df.columns.str.lower()
df.columns

Index(['order id', 'order date', 'ship mode', 'segment', 'country', 'city',
       'state', 'postal code', 'region', 'category', 'sub category',
       'product id', 'cost price', 'list price', 'quantity',
       'discount percent'],
      dtype='object')

In [66]:
#replacing the spaces with underscore
df.columns = df.columns.str.replace(" ","_")

In [67]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [80]:
#list the discount amount
#in the data we have the discount percentage but not the exact value
df['discount']=df["list_price"]*df["discount_percent"]*.01
df['discount']

0        5.2
1       21.9
2        0.5
3       19.2
4        1.0
        ...
9989     1.2
9990     3.6
9991     5.2
9992     0.9
9993     7.2
Name: discount, Length: 9994, dtype: float64

In [82]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,208.0,-32.0
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,511.0,-89.0
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,5.0,-5.0
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,768.0,-12.0
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,10.0,-10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,18.0,-12.0
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,54.0,-16.0
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,208.0,-12.0
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,21.0,-9.0
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,168.0,-42.0

In [83]:
#find out the sale_price
df['sale_price']= df['list_price']-df['discount']
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,-32.0
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,-89.0
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-5.0
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,-12.0
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-12.0
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,-16.0
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,-12.0
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-9.0
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,-42.0

In [84]:
#find out the total profit
df['profit'] = df['sale_price'] - df['cost_price']
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [91]:
#convert the date column which is in object to datetime
df['order_date']=pd.to_datetime(df['order_date'],format= "%Y-%m-%d")

In [98]:
df.dtypes

order_id                 int64
order_date      datetime64[ns]
ship_mode               object
segment                 object
country                 object
city                    object
state                   object
postal_code              int64
region                  object
category                object
sub_category            object
product_id              object
quantity                 int64
discount               float64
sale_price             float64
profit                 float64
dtype: object

In [101]:
#drop columns which are not in use
df.drop(columns=['list_price','cost_price','discount_percent'],inplace = True,errors='ignore')

In [102]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [103]:
!pip install sqlalchemy pyodbc

Requirement already satisfied: sqlalchemy in c:\users\windows\.anaconda\lib\site-packages (1.4.39)
Requirement already satisfied: pyodbc in c:\users\windows\.anaconda\lib\site-packages (4.0.34)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\windows\.anaconda\lib\site-packages (from sqlalchemy) (2.0.1)

In [106]:
#create the connection to load the data into sql server
import sqlalchemy as sal

engine = sal.create_engine(
    "mssql+pyodbc://SYEDAFREEN\\SQLEXPRESS/master?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes"
)
conn = engine.connect()

In [111]:
#load the data into sql server
df.to_sql('df_orders', con=conn , index=False, if_exists = 'append')

-1

In [110]:
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'quantity', 'discount', 'sale_price', 'profit'],
      dtype='object')